server:
  port: 8083

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:6603/db_example
    password: password;

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: pass
    realmImportFile: realm.json
